---
listing:
  contents: journalclub
  sort: "date desc"
  type: default
  categories: true
  feed: true
---

## Journal Club

The ASA Covariate Adjustment Working Group Journal Club convenes monthly, offering a vibrant forum for discussing the latest findings, challenges, or concepts related to covariate adjustment. Our gatherings alternate between two engaging formats:

1.  A roundtable where members delve into specific questions or issues they've encountered, and
2.  A seminar series featuring presentations on recent scholarly articles by our members or esteemed guest speakers.

These enriching sessions are held on the **second Friday of every month, from 11 am to 12 pm EDT**.

We warmly welcome and highly value your contributions, including topic suggestions, ideas, or feedback for future Journal Club meetings. Please share your thoughts with Bingkai Wang at [bingkai\@umich.edu](mailto:bingkai@umich.edu).

## Events

<!-- List of Journal Club activity: -->

<!-- 1.  Journal Club: Discussion on the FDA Guidance for Covariate Adjustment, 15 Mar 2024. [details](./posts/journalclub1.html) -->

<!-- 2.  \[Upcoming\] Journal Club: Variance Estimation for G-computation with Binary Outcomes, 12 Apr 2024. [details](./posts/journalclub2.html) -->
