---
title: "Covariate-Adjusted Randomization Analyzed with Randomization-Based Inference"
description: "Oct 2024 Journal Club by Jonathan Chipman"
author: ""
date: "10/11/2024"
draft: false
categories:
  - journal club
---

**Topic:** Covariate-Adjusted Randomization Analyzed with Randomization-Based Inference

**Datetime: Oct 11th Friday, 11am-12pm EDT.**

**Presenter:** Jonathan Chipman from University of Utah

**Summary:** Adjusting for covariates in the design and/or analysis can increase the efficiency of a randomized trial. While several model-based strategies for covariate adjustment have been developed---many of which can accommodate covariate-adjusted/adaptive randomization (CAR)---the potential benefits of CAR are less well understood, particularly regarding efficiency gains. Here, we examine the strengths and limitations of design-based covariate adjustment analyzed with randomization-based inference (i.e., CAR+RBI), review traditional and contemporary CAR methods, and provide a case study to assess the efficiency of CAR+RBI strategies. We ask the question: can adjusting for covariates only in the design be as powerful as adjusting for covariates only in the analysis?

The case study uses data from the REACH trial (n=512, 12-month continuous outcome with 9 baseline covariates explaining 32% of the outcome variance). We compare the power of CAR+RBI strategies to detect a beneficial treatment effect against that of complete randomization, analyzed with a comparable covariate-adjusted linear model. In this case study, biased-coin minimization CAR+RBI strategies were the most powerful strategies, suggesting that covariate adjustment in the design can be as effective as model-based covariate adjustment. While these findings are case-specific and results may differ across studies, they highlight the importance of further CAR and RBI research and consideration of implementation barriers.

This presentation summarizes the following paper, emphasizing the real-world application/case study.

Chipman JJ, Mayberry L, Greevy RA Jr (2023). Rematching on-the-fly: Sequential matched randomization and a case for covariate-adjusted randomization. Stat Med, 42(22), 3981-3995.

**Recording:** 
```{=html}
<iframe src="https://drive.google.com/file/d/1Bm5UVwhGRCuafHwgkIwBztb1wq0dN7CK/preview" width="640" height="480" allowfullscreen="true" allow="autoplay"></iframe>
```

```{=html}
<script src="https://giscus.app/client.js"
        data-repo="carswg/carswg.github.io"
        data-repo-id="R_kgDOLX8xOg"
        data-category="General"
        data-category-id="DIC_kwDOLX8xOs4CeZQB"
        data-mapping="title"
        data-strict="1"
        data-reactions-enabled="1"
        data-emit-metadata="0"
        data-input-position="bottom"
        data-theme="light_high_contrast"
        data-lang="en"
        crossorigin="anonymous"
        async>
</script>
```
